apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csp-cluster-xrds
  namespace: {{ .Values.namespace }}
  #finalizers:
  #  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.csp_cluster_xrds.destination.namespace }}
    server: {{ .Values.csp_cluster_xrds.destination.server }}
  project: {{ .Values.project }}
  source:
    path: {{ .Values.csp_cluster_xrds.path }}
    repoURL: {{ .Values.csp_cluster_xrds.repoURL }}
    targetRevision: HEAD