apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: divvy-xrds-new
  namespace: {{ .Values.namespace }}
  #finalizers:
  #  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.divvy_xrds_new.destination.namespace }}
    server: {{ .Values.divvy_xrds_new.destination.server }}
  project: {{ .Values.project }}
  source:
    path: {{ .Values.divvy_xrds_new.path }}
    repoURL: {{ .Values.divvy_xrds_new.repoURL }}
    targetRevision: HEAD